# Generated by Django 5.1.1 on 2024-09-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='total_amount',
        ),
    ]
