# Generated by Django 5.1.1 on 2024-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='product',
            field=models.ManyToManyField(related_name='product_ids', to='product.productmodel'),
        ),
    ]
